services:
  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    hostname: keycloak-server
    ports:
      - '9091:9091'
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgresql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: simppl
      KC_DB_PASSWORD: simppl
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --http-port=9091
    networks:
      - ${SIMPPL_NETWORK}
    depends_on:
      - postgresql
